/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tiesen.api

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication class App {}

fun main() {
  runApplication<App>()
}
